[[redirects]]
from = "/contact-kodi-team"
to = "/about/contact"

[[redirects]]
from = "/sponsors"
to = "/about/sponsors"

[[redirects]]
from = "/about/xbmc-foundation"
to = "/about/foundation"

[[redirects]]
from = "/addons/browse"
to = "/addons/nexus/search"

[[redirects]]
from = "/addon-top-authors"
to = "/addons/nexus/top-authors"

[[redirects]]
from = "/get-involved"
to = "/contribute"

[[redirects]]
from = "/contribute/donate"
to = "/donate"

[[redirects]]
from = "/corporate-enquires"
to = "/about/sponsors"

[[redirects]]
from = "/kodi-team"
to = "/about/team"

[[redirects]]
from = "/feed"
to = "rss.xml"

[[redirects]]
from = "/kodi-privacy-policy"
to = "/about/privacy-policy"
